### PR TITLE
 #545319 SXA Starter has been switched to SSG by default

### PR DESCRIPTION
**Pull request by StanislavStativa**
SXA Starter has been switched to SSG by default

### CODE REVIEW

**Comment by iamandycohen** [comment]
Is this meant for a live / delivery deployment only, for example to Vercel?  What about in experience editor, should this be disabled?  I'm trying to determine what the value should be set to on our RH deployments in XM Cloud Deploy.

**Comment by StanislavStativa** [comment]
> 

Hello Andy,

I think there is answer on this question in disscussions of the approproate PBI and you've got an answer. Am I right?

**Comment by StanislavStativa** [comment]
Hello @iamandycohen,

ENV variable has been added to RH deployment. So, our changes are ready to be merged

**Comment by iamandycohen** [comment]
As soon as that change is in Prod, no problem.

**Comment by StanislavStativa** [comment]
Hello @iamandycohen.

All changes are in Prod related to adding env variable.
This branch has been tested, task #549532

**Review by iamandycohen — DISMISSED** [review]

**Pull request merged**
